### ISSUE TITLE
TODOs planning

### ISSUE THREAD

**Issue by kuenishi** [kuenishi/presto-riak#1]
## TODOs
- [ ] sibling handling: can they be handled as multiple tuples?  or never use allow_mult, choose first, or whatever.
- [x] optimization: pushing-down predicates would make it  much faster; or changing index to find keys  or custom mapreduce each time? Anyway, for now  there are no means to know join keys or predicates  in the backend.
  => maybe HyperLogLog in Riak, or eleveldb ????
- [ ] currently OtpConnection is protected with `synchronized`  method in DirectConnection#call(). Needs change with  request id control.
- [x] nested JSON objects: handle it as a single column with  concatinated name. #11
- [ ] modes: PB API mode and direct mode. Direct mode using [jinterface](http://www.erlang.org/doc/apps/jinterface/java/index-all.html) seems now working while PB API mode is cut off. Needs rewrite.
- [ ] custom backend: bitcask nor leveldb are not optimized  for full scanning. A backend that supports columnar  data format like parquet / ORCFile would make it faster
- [ ] Write tests on everything
- [ ] Do it be more moderate Java library
- [ ] performance tests in real distributed enviroment
## DONE
- interface: how can we force users 2i properly set? - nothing.
## Compare
- [Optiq](https://wiki.apache.org/incubator/OptiqProposal)
